// Package healthgen generates the frontend's TypeScript copy of the Health
// display contract constants (docs/modules/controlplane.md: "constants are code-generated
// into the frontend via the api package, so the three ends cannot drift").
//
// The generator reads the api package SOURCE with go/ast rather than
// importing it and listing known identifiers: a constant added to the Go
// side then shows up here automatically, and the golden test fails until the
// checked-in TypeScript is regenerated. Importing the package would only
// prove that the generator repeats itself.
//
// Constraint: like everything under cmd/agenthub-gui, this package may not
// import internal/* (canonical.md §2 rule 1). It needs nothing beyond the
// standard library.
package healthgen

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// Group is one generated TypeScript enum-like object: the Go constants whose
// names start with Prefix become members of TSName with the prefix stripped.
type Group struct {
	// TSName is the exported TypeScript identifier.
	TSName string
	// Prefix is the Go constant name prefix that selects the members.
	Prefix string
	// Doc is the comment written above the generated object.
	Doc string
}

// Groups is the frozen list of generated groups. Adding a group here is a
// deliberate act; adding a CONSTANT to an existing group happens by itself.
var Groups = []Group{
	{
		TSName: "HealthLevel", Prefix: "HealthLevel",
		Doc: "Health.level values. Rendered verbatim: a frontend never re-derives\nstatus from connection flags (docs/modules/controlplane.md).",
	},
	{
		TSName: "AdminState", Prefix: "AdminState",
		Doc: "Health.admin_state values. disabled/quarantined keep level=healthy on\npurpose — intentionally off is not broken.",
	},
	{
		TSName: "HealthAction", Prefix: "Action",
		Doc: "Health.action values: the machine-readable suggested action that drives\nthe Servers page buttons. \"\" means there is nothing to do.",
	},
}

// Constant is one discovered Go constant.
type Constant struct {
	// GoName is the identifier in the api package.
	GoName string
	// TSName is GoName with the group prefix stripped.
	TSName string
	// Value is the string literal value.
	Value string
}

// Collected is the parse result: one entry per group, in Groups order.
type Collected struct {
	Group     Group
	Constants []Constant
}

// header is the generated-file banner. The first line matches the
// convention recognised by tooling ("^// Code generated .* DO NOT EDIT\.$").
const header = `// Code generated by cmd/agenthub-gui/internal/healthgen. DO NOT EDIT.
//
// Source of truth: the Health display contract constants in the Go package
// github.com/dinstein/agent-hub/api (docs/modules/controlplane.md). The daemon computes
// Health with one pure function and every frontend only renders it; these
// values are matched, never invented.
//
// Regenerate: go generate ./cmd/agenthub-gui/...
`

// Collect parses every .go file in apiDir (test files excluded) and returns
// the constants of each group.
//
// Failure direction: fail-closed. A group with no constants, a non-string
// constant or an unparsable file is an error — silently emitting a smaller
// set would produce a frontend that renders unknown states as blanks.
func Collect(apiDir string) ([]Collected, error) {
	entries, err := os.ReadDir(apiDir)
	if err != nil {
		return nil, fmt.Errorf("healthgen: reading %s: %w", apiDir, err)
	}
	// Deterministic order: files sorted by name (os.ReadDir already sorts),
	// declarations in source order. "Determinism is the contract"
	// (canonical.md §6).
	var names []string
	for _, e := range entries {
		n := e.Name()
		if e.IsDir() || !strings.HasSuffix(n, ".go") || strings.HasSuffix(n, "_test.go") {
			continue
		}
		names = append(names, filepath.Join(apiDir, n))
	}
	if len(names) == 0 {
		return nil, fmt.Errorf("healthgen: no Go files in %s", apiDir)
	}

	type found struct {
		name, value string
	}
	var all []found
	fset := token.NewFileSet()
	for _, name := range names {
		file, err := parser.ParseFile(fset, name, nil, parser.SkipObjectResolution)
		if err != nil {
			return nil, fmt.Errorf("healthgen: parsing %s: %w", name, err)
		}
		if file.Name.Name != "api" {
			return nil, fmt.Errorf("healthgen: %s declares package %s, want api", name, file.Name.Name)
		}
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.CONST {
				continue
			}
			for _, spec := range gd.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok || len(vs.Names) != len(vs.Values) {
					continue
				}
				for i, id := range vs.Names {
					if !id.IsExported() {
						continue
					}
					lit, ok := vs.Values[i].(*ast.BasicLit)
					if !ok || lit.Kind != token.STRING {
						continue
					}
					v, err := strconv.Unquote(lit.Value)
					if err != nil {
						return nil, fmt.Errorf("healthgen: %s: unquoting %s: %w", name, id.Name, err)
					}
					all = append(all, found{id.Name, v})
				}
			}
		}
	}

	out := make([]Collected, 0, len(Groups))
	for _, g := range Groups {
		c := Collected{Group: g}
		for _, f := range all {
			if !strings.HasPrefix(f.name, g.Prefix) || f.name == g.Prefix {
				continue
			}
			c.Constants = append(c.Constants, Constant{
				GoName: f.name,
				TSName: strings.TrimPrefix(f.name, g.Prefix),
				Value:  f.value,
			})
		}
		if len(c.Constants) == 0 {
			return nil, fmt.Errorf("healthgen: no constants with prefix %q in %s", g.Prefix, apiDir)
		}
		out = append(out, c)
	}
	return out, nil
}

// Render emits the TypeScript module for the collected constants.
func Render(groups []Collected) []byte {
	var b bytes.Buffer
	b.WriteString(header)
	for _, g := range groups {
		b.WriteString("\n")
		for _, line := range strings.Split(g.Group.Doc, "\n") {
			b.WriteString("// " + line + "\n")
		}
		fmt.Fprintf(&b, "export const %s = {\n", g.Group.TSName)
		for _, c := range g.Constants {
			fmt.Fprintf(&b, "  %s: %s,\n", c.TSName, strconv.Quote(c.Value))
		}
		b.WriteString("} as const;\n\n")
		fmt.Fprintf(&b, "export type %s = (typeof %s)[keyof typeof %s];\n",
			g.Group.TSName, g.Group.TSName, g.Group.TSName)
		b.WriteString("\n")
		fmt.Fprintf(&b, "export const %sValues: readonly %s[] = [\n",
			g.Group.TSName, g.Group.TSName)
		for _, c := range g.Constants {
			fmt.Fprintf(&b, "  %s.%s,\n", g.Group.TSName, c.TSName)
		}
		b.WriteString("];\n")
	}
	return b.Bytes()
}

// Generate parses apiDir and returns the TypeScript module bytes.
func Generate(apiDir string) ([]byte, error) {
	groups, err := Collect(apiDir)
	if err != nil {
		return nil, err
	}
	return Render(groups), nil
}

// WriteFile generates the module and writes it to out, creating parent
// directories as needed. The write is atomic (temp file in the destination
// directory, then rename) so an interrupted run never leaves a half-written
// file that the frontend build would happily compile.
func WriteFile(apiDir, out string) error {
	data, err := Generate(apiDir)
	if err != nil {
		return err
	}
	dir := filepath.Dir(out)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("healthgen: creating %s: %w", dir, err)
	}
	tmp, err := os.CreateTemp(dir, ".healthgen-*")
	if err != nil {
		return fmt.Errorf("healthgen: temp file: %w", err)
	}
	name := tmp.Name()
	defer func() { _ = os.Remove(name) }() // no-op after a successful rename
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("healthgen: writing %s: %w", name, err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("healthgen: closing %s: %w", name, err)
	}
	if err := os.Chmod(name, 0o644); err != nil {
		return fmt.Errorf("healthgen: chmod %s: %w", name, err)
	}
	if err := os.Rename(name, out); err != nil {
		return fmt.Errorf("healthgen: renaming to %s: %w", out, err)
	}
	return nil
}
