package healthgen_test

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/dinstein/agent-hub/api"
	"github.com/dinstein/agent-hub/cmd/agenthub-gui/internal/healthgen"
)

// repoPath resolves a path relative to the repository root from this test
// file's location (…/cmd/agenthub-gui/internal/healthgen).
func repoPath(t *testing.T, rel ...string) string {
	t.Helper()
	_, self, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	root := filepath.Join(filepath.Dir(self), "..", "..", "..", "..")
	return filepath.Join(append([]string{root}, rel...)...)
}

func collect(t *testing.T) map[string]string {
	t.Helper()
	groups, err := healthgen.Collect(repoPath(t, "api"))
	if err != nil {
		t.Fatalf("Collect: %v", err)
	}
	got := map[string]string{}
	for _, g := range groups {
		for _, c := range g.Constants {
			if prev, dup := got[c.GoName]; dup {
				t.Errorf("constant %s collected twice (%q, %q)", c.GoName, prev, c.Value)
			}
			got[c.GoName] = c.Value
		}
	}
	return got
}

// TestCollectedConstantsMatchGoPackage is the anti-drift assertion: the
// values the generator parses out of the api SOURCE must equal the values
// the compiler sees. It also pins the SET of constants — a new HealthLevel*
// / AdminState* / Action* constant fails here until it is listed, so it can
// never reach the wire without the frontend learning about it (docs/subsystems/docs/subsystems/controlplane.md
// : no drift between the three ends).
func TestCollectedConstantsMatchGoPackage(t *testing.T) {
	want := map[string]string{
		"HealthLevelHealthy":   api.HealthLevelHealthy,
		"HealthLevelDegraded":  api.HealthLevelDegraded,
		"HealthLevelUnhealthy": api.HealthLevelUnhealthy,
		"AdminStateEnabled":    api.AdminStateEnabled,
		"AdminStateDisabled":   api.AdminStateDisabled,
		"ActionLogin":          api.ActionLogin,
		"ActionRefresh":        api.ActionRefresh,
		"ActionRestart":        api.ActionRestart,
		"ActionEnable":         api.ActionEnable,
		"ActionSetSecret":      api.ActionSetSecret,
		"ActionViewLogs":       api.ActionViewLogs,
		"ActionNone":           api.ActionNone,
	}
	got := collect(t)
	for name, value := range want {
		v, ok := got[name]
		if !ok {
			t.Errorf("generator missed constant %s", name)
			continue
		}
		if v != value {
			t.Errorf("%s = %q, compiler says %q", name, v, value)
		}
	}
	for name := range got {
		if _, ok := want[name]; !ok {
			t.Errorf("api gained constant %s: add it here and regenerate "+
				"(go generate ./cmd/agenthub-gui/...)", name)
		}
	}
}

// TestGeneratedFileIsUpToDate is the golden test: the checked-in TypeScript
// must be byte-identical to a fresh generation. It fails both when someone
// edits the generated file by hand and when an api constant changes without
// regenerating.
func TestGeneratedFileIsUpToDate(t *testing.T) {
	want, err := healthgen.Generate(repoPath(t, "api"))
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	path := repoPath(t, "cmd", "agenthub-gui", "frontend", "src", "generated", "health.ts")
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	if string(got) != string(want) {
		t.Errorf("%s is stale; run `go generate ./cmd/agenthub-gui/...`\n--- got ---\n%s\n--- want ---\n%s",
			path, got, want)
	}
}

// TestRenderShape pins the emitted TypeScript shape: the frontend imports
// these identifiers, so their names are part of the contract.
func TestRenderShape(t *testing.T) {
	out, err := healthgen.Generate(repoPath(t, "api"))
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	s := string(out)
	for _, want := range []string{
		"// Code generated by cmd/agenthub-gui/internal/healthgen. DO NOT EDIT.",
		"export const HealthLevel = {",
		"export type HealthLevel = (typeof HealthLevel)[keyof typeof HealthLevel];",
		"export const HealthLevelValues: readonly HealthLevel[] = [",
		"export const AdminState = {",
		"export const HealthAction = {",
		`  SetSecret: "set_secret",`,
		`  None: "",`,
	} {
		if !strings.Contains(s, want) {
			t.Errorf("generated module is missing %q", want)
		}
	}
}

// TestWriteFileIsAtomicAndCreatesDirs covers the write path the generator
// command uses: parent directories are created and the result matches
// Generate byte for byte.
func TestWriteFileIsAtomicAndCreatesDirs(t *testing.T) {
	out := filepath.Join(t.TempDir(), "nested", "dir", "health.ts")
	if err := healthgen.WriteFile(repoPath(t, "api"), out); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}
	got, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("reading %s: %v", out, err)
	}
	want, err := healthgen.Generate(repoPath(t, "api"))
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if string(got) != string(want) {
		t.Error("WriteFile output differs from Generate")
	}
	// No temp files left behind.
	entries, err := os.ReadDir(filepath.Dir(out))
	if err != nil {
		t.Fatalf("ReadDir: %v", err)
	}
	if len(entries) != 1 {
		t.Errorf("expected exactly one file in the output dir, got %d", len(entries))
	}
}

// TestCollectFailsClosed: a directory that is not the api package is an
// error, never an empty (and silently wrong) result.
func TestCollectFailsClosed(t *testing.T) {
	if _, err := healthgen.Collect(t.TempDir()); err == nil {
		t.Error("Collect on an empty directory: want error, got nil")
	}
	if _, err := healthgen.Collect(repoPath(t, "cmd", "agenthub-gui", "services")); err == nil {
		t.Error("Collect on a non-api package: want error, got nil")
	}
}
