#!/usr/bin/env bash
#
# Render the Homebrew formula for a released version.
#
#   scripts/homebrew-formula.sh <release-tag> <checksums-cli.txt> > agenthub.rb
#
# The formula installs the PREBUILT binary from the GitHub release rather than
# building from source, and that is a deliberate choice about one flag.
#
# `-X main.channel=release` is what sends a shipped binary to the real data
# directory; the default is `dev`, which is correct for a working tree and
# wrong for a download. Today that flag is set in exactly one place — the
# release workflow. A source-building formula would have to restate it, and if
# it ever failed to, every brew user would silently get the DEVELOPMENT data
# directory. The symptom is "all my servers disappeared", which nobody traces
# back to a build flag. Installing the same artifact CI already built keeps the
# channel decision in one place.
#
# The asset names carry version-and-hash (agenthub-0.2.1-abc1234-darwin-arm64
# .tar.gz), so the full string is read out of the checksums file instead of
# being reconstructed here — two places computing the same name is how a
# formula ends up pointing at a URL that does not exist.

set -euo pipefail

if [ $# -ne 2 ]; then
	echo "usage: $0 <release-tag> <checksums-cli.txt>" >&2
	exit 2
fi

tag="$1"
sums="$2"
repo="${HOMEBREW_SOURCE_REPO:-dinstein/agent-hub}"

if [ ! -r "$sums" ]; then
	echo "$0: cannot read checksums file: $sums" >&2
	exit 1
fi

# The x.y.z half, without the leading v and without the commit hash.
version="${tag#v}"

# sha_for <os> <arch> — the checksum line for one platform, or empty.
sha_for() {
	awk -v pat="-$1-$2.tar.gz" '$2 ~ pat {print $1}' "$sums" | head -1
}

# asset_for <os> <arch> — the file name, read back rather than recomposed.
asset_for() {
	# sub(): a checksums file written with a ./* glob carries a "./" prefix on
	# every name, which lands in the URL as a stray "/./" and 404s. Strip it
	# here as well as at the source: this reads files it did not write.
	awk -v pat="-$1-$2.tar.gz" '$2 ~ pat {sub(/^\.\//, "", $2); print $2}' "$sums" | head -1
}

# Every platform brew supports must be present. A formula that silently omits
# one arch installs nothing on that machine and reports it as "no bottle".
missing=""
for target in darwin-amd64 darwin-arm64 linux-amd64 linux-arm64; do
	os="${target%-*}"
	arch="${target#*-}"
	[ -n "$(sha_for "$os" "$arch")" ] || missing="$missing $target"
done
if [ -n "$missing" ]; then
	echo "$0: no checksum for:$missing" >&2
	echo "$0: the release is incomplete; refusing to render a formula that 404s" >&2
	exit 1
fi

base="https://github.com/${repo}/releases/download/${tag}"

block() { # block <os> <arch>
	printf '      url "%s/%s"\n' "$base" "$(asset_for "$1" "$2")"
	printf '      sha256 "%s"\n' "$(sha_for "$1" "$2")"
}

cat <<EOF
# Generated by scripts/homebrew-formula.sh from the ${tag} release. Do not edit
# by hand: the next release overwrites it, and a hand-edited sha256 that no
# longer matches its URL fails at install time on someone else's machine.
class Agenthub < Formula
  desc "Local gateway between AI clients and MCP servers"
  homepage "https://github.com/${repo}"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
$(block darwin arm64)
    end
    on_intel do
$(block darwin amd64)
    end
  end

  on_linux do
    on_arm do
$(block linux arm64)
    end
    on_intel do
$(block linux amd64)
    end
  end

  def install
    bin.install "agenthub"
  end

  def caveats
    <<~EOS
      Point an AI client at the gateway (this edits that client's own config,
      so look at it first):

        agenthub client detect
        agenthub client connect claude-code --dry-run
        agenthub client connect claude-code

      Then restart the client. Servers added later need no further client
      changes — that is the point of the gateway.
    EOS
  end

  test do
    out = shell_output("#{bin}/agenthub --version")
    assert_match version.to_s, out

    # A release build must NOT be a dev build. The channel is a link-time flag,
    # so the only way to be sure the shipped artifact resolves the real data
    # directory is to ask the binary. Getting this wrong is silent: the user
    # keeps their config in AgentHubDev and reports that everything vanished.
    refute_match "(dev)", out

    # Exit 4 is "daemon offline", the correct answer on a machine that has
    # never started one. shell_output asserts the status itself, so this
    # proves the binary runs and classifies rather than only printing a
    # version string.
    shell_output("#{bin}/agenthub daemon status", 4)
  end
end
EOF
