#!/usr/bin/env bash
#
# Put this release's tap-facing files into a tap checkout, as ONE commit.
#
#   scripts/tap-sync.sh <tap-checkout> <tag> [<formula.rb> [<cask.rb>]]
#
# Three files travel to the tap and they are not independent:
# Formula/agenthub.rb installs a binary, Casks/agenthub-gui.rb installs the app
# that drives it and DEPENDS ON that formula, and skills/agenthub/SKILL.md tells
# an AI client how to drive the binary. The skill is written against a specific
# released surface — it says so in its own second paragraph — so a tap where
# they arrive in separate commits has a window in which `git show` on any one of
# them describes a version the others do not. One commit closes it.
#
# For the cask that window is worse than a documentation lag: an install landing
# inside it gets this release's app resolving a dependency the tap still
# describes at the previous release.
#
# WHY THIS IS A SCRIPT AND NOT TWO COPIES OF A `cp`. The release workflow and
# scripts/release-local.sh both update the tap, and the same reasoning that put
# the build loop in build-release-artifacts.sh applies here: two implementations
# of "which files go to the tap" drift the moment a third file is added, and the
# one that was forgotten is invisible — the tap still updates, still commits,
# still pushes, and simply serves a stale copy of whatever nobody remembered.
# test/buildrules asserts both callers come through here.
#
# OMITTING THE FORMULA is the out-of-band path. The skill's revisions land
# faster than releases do (four in the day 0.11.0 and 0.12.0 shipped), and
# without this the only way to publish a doc fix would be to cut a version that
# changes no code. The tag is still required and still means the same thing: the
# release the skill was verified against.
#
# OMITTING THE CASK is release-local.sh's path, and is not an oversight: that
# script builds no DMG, so it has nothing to point a cask at. The tap then keeps
# serving the previous release's app beside a newer formula. That is survivable
# — the cask's depends_on carries no version — and it is why the dependency is
# spelled without one; a cask left behind must degrade to "the GUI is a release
# older", never to "the GUI will not install".

set -euo pipefail

if [ $# -lt 2 ] || [ $# -gt 4 ]; then
	echo "usage: $0 <tap-checkout> <tag> [<formula.rb> [<cask.rb>]]" >&2
	exit 2
fi

tap="$1"
tag="$2"
formula="${3:-}"
cask="${4:-}"

# A cask without a formula would publish an app whose dependency the same
# commit does not update. Ordering the arguments cannot prevent it — this can.
if [ -n "$cask" ] && [ -z "$formula" ]; then
	echo "$0: a cask was given without a formula" >&2
	echo "$0: the cask depends on the formula; publishing one without the other is" >&2
	echo "$0: the split commit this script exists to prevent, spelled differently" >&2
	exit 2
fi
here="$(cd "$(dirname "$0")/.." && pwd)"
skill="$here/skills/agenthub/SKILL.md"

case "$tag" in
v*) ;;
*)
	echo "$0: tag must start with v (got ${tag})" >&2
	exit 2
	;;
esac

if [ ! -d "$tap/.git" ]; then
	echo "$0: not a git checkout: $tap" >&2
	exit 1
fi

# Hard failure rather than "sync whatever is there". A release that quietly
# shipped no skill would leave the tap serving documentation for an older CLI,
# and the symptom lands in someone else's client as a flag that does not exist.
if [ ! -r "$skill" ]; then
	echo "$0: cannot read the skill: $skill" >&2
	echo "$0: it is the repository's copy and the tap's is generated from it;" >&2
	echo "$0: refusing to publish a release that leaves the tap's copy behind" >&2
	exit 1
fi

if [ -n "$formula" ] && [ ! -r "$formula" ]; then
	echo "$0: cannot read the formula: $formula" >&2
	exit 1
fi

if [ -n "$cask" ] && [ ! -r "$cask" ]; then
	echo "$0: cannot read the cask: $cask" >&2
	exit 1
fi

# The banner is the only difference between the two copies, and it exists for
# the same reason the formula's does: this file used to BE maintained in the
# tap, so the habit it has to break is real rather than hypothetical. An HTML
# comment renders as nothing and carries no meaning into the skill itself.
#
# It goes after the YAML frontmatter, not before it: a skill whose first line
# is not `---` has no frontmatter as far as a client's parser is concerned, and
# the whole file stops being a skill.
banner="<!-- Generated by scripts/tap-sync.sh from the agent-hub repository at ${tag}."
banner="${banner} Do not edit here: the next release overwrites it, and the edit is lost"
banner="${banner} without ever appearing in a diff anyone reads. -->"

head -1 "$skill" | grep -qx -- '---' || {
	echo "$0: ${skill} does not open with YAML frontmatter" >&2
	echo "$0: a client will not load it as a skill; refusing to publish it" >&2
	exit 1
}

mkdir -p "$tap/skills/agenthub"
# NR>1 so the opening delimiter is not mistaken for the closing one; the flag
# makes it fire exactly once, on the close.
#
# `version:` is injected into the frontmatter, not the body: it is metadata
# about THIS copy — which CLI release it was generated for — not a fact about
# the skill document itself. The source file has no version field, and adding
# one there would require someone to keep it in sync manually; generating it
# here means it is always right for free. Placing it last, just before the
# closing delimiter, keeps the two human-maintained fields (name, description)
# at the top where they are read first.
awk -v banner="$banner" -v ver="$tag" '
	NR > 1 && !done && /^---$/ { print "version: " ver; print; print ""; print banner; done = 1; next }
	{ print }
' "$skill" > "$tap/skills/agenthub/SKILL.md"

if [ -n "$formula" ]; then
	mkdir -p "$tap/Formula"
	cp "$formula" "$tap/Formula/agenthub.rb"
fi

# agenthub-gui, not agenthub: the token has to differ from the formula's, or
# `brew install agenthub` becomes an ambiguous name in one tap and Homebrew
# picks for the user.
if [ -n "$cask" ]; then
	mkdir -p "$tap/Casks"
	cp "$cask" "$tap/Casks/agenthub-gui.rb"
fi

cd "$tap"

# STAGE FIRST, THEN COMPARE. `git diff` without --cached does not see untracked
# files, so a path arriving in the tap for the FIRST time — the skill did, and
# the next file to be added will — reads as "no change" and the script exits
# reporting success while pushing nothing. That is the exact failure this
# script exists to prevent, wearing a green tick.
git add -A -- Formula Casks skills

# Re-running a release must not produce an empty commit.
if git diff --cached --quiet -- Formula Casks skills; then
	echo "the tap already matches ${tag}; nothing to push"
	exit 0
fi

# Only when there is none. CI has no identity and must be given one; a
# developer running release-local.sh has their own, and a script that
# overwrote it would attribute their commit to a bot that does not exist.
git config user.name >/dev/null 2>&1 || git config user.name "agenthub release"
git config user.email >/dev/null 2>&1 || git config user.email "noreply@github.com"
if [ -n "$formula" ]; then
	git commit -q -m "agenthub ${tag}"
else
	git commit -q -m "docs(skill): sync at ${tag}"
fi
git push

echo "pushed to the tap:"
git show --stat --oneline HEAD | sed 's/^/  /'
