package secrets

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"strconv"
	"sync"
	"testing"
)

// TestMultiProcessVaultWritesAllSurvive is the acceptance test ruling A.3 #1
// requires of cross-process shared state.
//
// N processes write into one vault directory, each under its own key prefix,
// so no write legitimately replaces another. Before the vault lock, every
// write was a whole-file read-modify-write of secrets.enc: two processes
// racing each loaded the map, added their own key and saved it back, and the
// slower save erased whatever the faster one had just added. What was erased
// was a credential, and nothing anywhere said so.
//
// The assertion is exact — every entry every process wrote must be readable
// afterwards. A missing one means a lost update; there is no acceptable
// number of them.
func TestMultiProcessVaultWritesAllSurvive(t *testing.T) {
	if testing.Short() {
		t.Skip("re-execs the test binary")
	}
	const (
		procs   = 4
		entries = 15
	)
	dir := t.TempDir()

	var (
		wg    sync.WaitGroup
		mu    sync.Mutex
		fails []string
	)
	start := make(chan struct{})
	for p := range procs {
		wg.Add(1)
		go func() {
			defer wg.Done()
			cmd := exec.Command(os.Args[0])
			cmd.Env = append(os.Environ(),
				helperModeEnv+"=set",
				helperDirEnv+"="+dir,
				helperNEnv+"="+strconv.Itoa(entries),
				helperPrefixEnv+"=p"+strconv.Itoa(p),
			)
			var out, errb bytes.Buffer
			cmd.Stdout = &out
			cmd.Stderr = &errb
			<-start
			if err := cmd.Run(); err != nil {
				mu.Lock()
				fails = append(fails, fmt.Sprintf("helper p%d: %v: %s%s", p, err, errb.String(), out.String()))
				mu.Unlock()
			}
		}()
	}
	close(start)
	wg.Wait()

	for _, f := range fails {
		t.Fatal(f)
	}

	// Read the finished vault back from a fresh chain, exactly as a later
	// agenthub process would.
	c := NewChain(ChainConfig{
		Dir:       dir,
		LookupEnv: envOf(map[string]string{EnvDevSecrets: "1"}),
		Keyring:   newFakeBackend(nil),
	})
	var missing []string
	for p := range procs {
		prefix := "p" + strconv.Itoa(p)
		for i := range entries {
			ref := Ref{ServerID: "srv", Key: fmt.Sprintf("%s-%d", prefix, i)}
			val, ok, err := c.Get(t.Context(), ref)
			if err != nil {
				t.Fatalf("read back %s: %v", ref.Key, err)
			}
			if !ok || val != prefix {
				missing = append(missing, ref.Key)
			}
		}
	}
	if len(missing) > 0 {
		t.Fatalf("%d of %d entries did not survive %d concurrent writer processes: %v\n"+
			"a missing entry is one process's read-modify-write erasing another's — the lost "+
			"credential the vault lock exists to prevent",
			len(missing), procs*entries, procs, missing)
	}
}

// The dev key is generated by a read-then-create on the first write, so N
// processes starting against an empty vault all reach it at once. If two
// generate their own, the second overwrites the first's file and the enc file
// sealed under the first key can never be opened again — the whole vault, not
// one entry. The test above would catch that as total failure; this one names
// it, so the diagnosis does not have to be reconstructed.
func TestMultiProcessDevKeyIsGeneratedOnce(t *testing.T) {
	if testing.Short() {
		t.Skip("re-execs the test binary")
	}
	const procs = 4
	dir := t.TempDir()

	var wg sync.WaitGroup
	start := make(chan struct{})
	errs := make([]string, procs)
	for p := range procs {
		wg.Add(1)
		go func() {
			defer wg.Done()
			cmd := exec.Command(os.Args[0])
			cmd.Env = append(os.Environ(),
				helperModeEnv+"=set",
				helperDirEnv+"="+dir,
				helperNEnv+"=1",
				helperPrefixEnv+"=k"+strconv.Itoa(p),
			)
			var errb bytes.Buffer
			cmd.Stderr = &errb
			<-start
			if err := cmd.Run(); err != nil {
				errs[p] = fmt.Sprintf("helper k%d: %v: %s", p, err, errb.String())
			}
		}()
	}
	close(start)
	wg.Wait()
	for _, e := range errs {
		if e != "" {
			t.Fatal(e)
		}
	}

	// One key file, and it opens the enc file every helper wrote through.
	c := NewChain(ChainConfig{
		Dir:       dir,
		LookupEnv: envOf(map[string]string{EnvDevSecrets: "1"}),
		Keyring:   newFakeBackend(nil),
	})
	for p := range procs {
		prefix := "k" + strconv.Itoa(p)
		val, ok, err := c.Get(t.Context(), Ref{ServerID: "srv", Key: prefix + "-0"})
		if err != nil {
			t.Fatalf("read back %s: %v (a second dev key would present exactly here)", prefix, err)
		}
		if !ok || val != prefix {
			t.Fatalf("entry from %s is gone: the vault was sealed under a key another process replaced", prefix)
		}
	}
	if _, err := os.Stat(VaultLockPath(dir)); err != nil {
		t.Fatalf("stat vault lock: %v", err)
	}
}
